### ISSUE TITLE
Add: 현대 슈퍼에어로시티 저상

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanBusSet#1]
![현대저상1](https://user-images.githubusercontent.com/10726524/112626795-09ff2a00-8e74-11eb-9e87-ae41d3b0f392.png)

**Comment by kimgas** [comment]
![aero_low](https://user-images.githubusercontent.com/79271602/113017138-1eb42880-91ba-11eb-92ef-bb9847751a08.png)

색상 개선 (2008~2017)

중간에 자잘한 변화가 있었지만 도트의 한계로 생략됐습니다.

참고- 색상 적용시기
서울: 2005년
경기: 2006년
천안: ?
부산(구): 2000년
부산(신): 2016년

**Comment by telk5093** [comment]
색상 개선이라는 게, 위의 스프라이트를 쓰지 말고 아래의 스프라이트를 써달라는 말씀이신 거죠?

**Comment by telk5093** [comment]
@kimgas 지금 이슈에 올라가있는 차량들의 레퍼런스 이미지와 링크를 첨부해주실 수 있을까요?
모델/도색 이름을 결정해야 하고, 색상 교체를 사용할지 말지도 결정해야 해서요.

**Comment by telk5093** [comment]
c290a0e 에서 구현되었습니다.

@kimgas
https://github.com/KoreanGRF/KoreanBusSet/actions/runs/764311855 에서 해당 버스만 추가된 grf를 받아서 테스트해보실 수 있습니다.
회사 색상 하나만 지원하면 여러 색으로 변경하는 방법을 적용해봤습니다.
다만 도색 목록이 37개로 매우 많아서 현재 구현된 도색 개조 목록 상태에 대한 생각을 여쭤보고 싶습니다.

**Comment by kimgas** [comment]
@telk5093 

1. 구동을 해본 결과..
아무래도 모든 색상을 구현하면 데이터가 너무 방대하게 늘어날 것 같습니다.
앞으로 추가 될 차량이나 색상 등을 고려하자면 실제로 존재하는 색상만 넣는게 맞다고 봅니다.
해당 색상이 별도로 필요하면 따로 변경 해서 올릴 수 있습니다.

2. 사용된 차량은 현대 슈퍼에어로시티 저상 2008~2014 입니다.
세세한 부분에서는 매년 바뀐 것이 있지만 게임에서는 생략해도 괜찮을 것 같습니다.

**Comment by telk5093** [comment]
서울은 짙은 파란색(dark blue), 노란색, 빨간색, , 경기도는 옅은 녹색(pale green)으로 설정하는 등 실제 존재하는 색상을 현 상황에서 충분히 커버할 수 있는 것 같습니다. 개인적으로는 다양한 색상을 고를 수 있어서 지금 상태가 꽤 나쁘지 않은 느낌입니다.

**Comment by kimgas** [comment]
1. 제조사 색상은 빼는 것을 건의합니다. 자세히 보면 차이가 있지만 두드러질 정도로 차이가 나지는 않기 때문에 굳이 있을 필요는 없다고 생각됩니다.
![EzMvOVwVEAI3jsC](https://user-images.githubusercontent.com/79271602/115880144-5c3c6680-a485-11eb-8bdb-33d582a90401.jpg)
무도색 차량을 올렸던건 다른분들이 이걸 이용해서 색상을 입힐 수 있게 한 의도였습니다.

2. 차후 타 지역들의 색상도 추가될 시 목록이 더 길어질텐데 이건 어떻게 할지 결정을 해야 할 것 같습니다. 아마 대부분 지역들은 고정색상이 될 것 같습니다.

3. 페이스리프트나 연식변경 등으로 인해 외관이나 스펙이 변한 경우 목록의 그래픽이 바뀌는 방향으로 갈지, 새로운 목록을 추가할지에 대해서도 결정이 필요해보입니다.

**Comment by telk5093** [comment]
1. manufacturer 도색은 제외하겠습니다.
2. 다른 NewGRF에도 이 정도로 긴 도색 개조 목록을 가진 grf가 있긴 있는 걸로 압니다.  다른 지역이 고정 색상이라면 이대로 둬도 될 것 같습니다.
3. 구입 목록의 차량은 최소화하고 도색 개조 목록을 늘리는 방식으로 가고자 합니다.

**Comment by kimgas** [comment]
![aero_low](https://user-images.githubusercontent.com/79271602/115990150-c297c500-a5fc-11eb-8953-07e4f55afa7f.png)

서울 도색이 여러 지역에서 쓰이는 관계로 기본도색으로 바꿔봤습니다.
코딩은 뜻대로 하시면 될 것 같습니다.

하는 김에 자잘한 수정하고 지역 몇 개를 추가했습니다.

기본색상
https://t1.daumcdn.net/cfile/blog/1872A7504D4C19BA1B

경기 06~
https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99C4453D5AC09F4E09

경기 20~
https://file1.bobaedream.co.kr/truck/2021/01/23/23/AxwN1611411230_890654388.jpg

천안
https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F23140C3D50F270A223

부산 00~
https://i.ytimg.com/vi/7Sl8jeeXNKg/maxresdefault.jpg

부산 17~
https://t1.daumcdn.net/cfile/blog/99F912505DBA663E3B

광주 1
https://file1.bobaedream.co.kr/truck/2013/06/21/10/fo411371778543.jpg

광주2
https://coresos-phinf.pstatic.net/a/329ia6/5_f7iUd018svc7omflhsscgw7_t7h8v3.jpg?type=w520

울산
https://file1.bobaedream.co.kr/multi_image/truck/2011/08/16/02/dudc1313430015.jpg

충북
https://obj-sg.thewiki.kr/data/ecb2adeca3bc3834312e6a7067.jpg

**Comment by telk5093** [comment]
@kimgas 
https://github.com/KoreanGRF/KoreanBusSet/suites/2606332484/artifacts/57030846
서울/경기도는 회사 색상을 적용해야 해서 도색이 많아지는 관계로 별도 차량으로 분리해보았습니다.
``2018~`` 부분의 그래픽만 적용했습니다. (서울/경기도 버스에는 ``2008~2014``와 ``2015~2017`` 그래픽 스프라이트를 더미 데이터로만 넣어둠)
확인해보시고 의견 주십시오.

**Comment by kimgas** [comment]
@telk5093 
1. 도색
모든 색상을 전부 표현하기에는 아무래도 과해지는 것 같습니다.
종합적으로 판단해서 저는 아래 두 의견을 내보고자 합니다.
 - 1안: 서울 기반에서 모든 색상을 가능하게 하고, 경기 포함 타 지역 모두 삭제 (한철셋식, 서울 명칭 삭제)
 - 2안: 서울,경기에서 실재하는 색상만 가능하게 하고, 이외 지역 모두 추가 (고증식, 서울 명칭 삭제)

2. 차량 스펙은 아래와 같이 하는게 좋을 것 같습니다. (현대저상2018 기준이며, 괄호 안은 실제 제원)
가격 $13,000 추천(60% 계산), (2008: 약 180,000,000원 ->2020: 약 215,000,000원)
중량 공차12, 만차17
최고속력 80km
힘 290마력
견인력 34kn, 계산근거없음 (120kgm)
유지비 $1,300 추천, 차값의 1/10으로 반영
수송량 65 (45)
개발 2018
수명 12년 추천, (11년6개월)
새 차량 그래픽을 넣을때마다 추천 제원을 같이 넣어서 올리겠습니다.

3. 연식변경은 그래픽이 바뀌는 것으로 반영되어도 될 것 같습니다. 사소한 제원도 바뀔 수 있으면 좋겠구요. 
4. 매개변수를 통해서 승차정원에 변동을 줄 수 있으면 좋을 것 같습니다.

**Comment by telk5093** [comment]
1. 2안의 ``회사 색상 + 서울 G/R/Y/B + 경기 실제 색상 + 이외 지역``이 차라리 낫겠네요.
 2. 가격/유지비는 $13,000, $1,300 이런 식으로 지정하는 게 아니고 자연숫값으로 입력하는지라 정확하게 해당 가격으로 정하는 것은 불가능하지만 최대한 비슷하게 맞춰보겠습니다.
 만차 중량은 설정이 불가능합니다. (알아서 무게가 늘어남)
 도입 시기는 2018년보다는 2008년이 낫지 않을까요.
 3. 연식 변경을 도입하면 결국 (플레이를 하다보면) 2018년 이후 차량이 대부분이 되는데 그게 괜찮을지 모르겠네요.
 기술적으로는 ``build_year`` 속성을 이용하면 가능합니다.
 4. 그건 이미 가능하고 앞으로도 가능할 겁니다 ;)

**Comment by telk5093** [comment]
@kimgas 
![image](https://user-images.githubusercontent.com/10726524/121127408-ad9d8b00-c864-11eb-868e-5903927ae977.png)
제공해주신 그래픽 스프라이트를 위 그림과 같이 반영할 예정입니다.
 * 빨간색 DUMMY: 파일은 들어가지만 실제 게임에서는 나오지 않는 더미 데이터
 * 빨간색 동그라미: 반영됨
 * 빨간색 동그라미 + 분홍색 화살표: ``build_year`` 속성을 이용해서, 구입 시기에 따라 화살표 방향 순서대로 그래픽이 바뀌게 반영
 * 빨간색 가위표: 반영되지 않고 버려질 예정

**Comment by telk5093** [comment]
Staled, close
