### ISSUE TITLE
일부 버스들의 비정상적인 속도

### ISSUE THREAD

**Issue by mintpies** [KoreanGRF/KoreanBusSet#16]
**대우 NEW BS110 저상 버스**, **현대 수퍼에어로시티 저상 버스** 의 속도가 기본값(5)로 설정하였음에도 643km/h의 속도로 표시되어있습니다.
![image](https://user-images.githubusercontent.com/74120838/151702431-d3167081-2651-4422-a9c4-192bc754292a.png)

![image](https://user-images.githubusercontent.com/74120838/151702554-d4cca2c1-acdb-48c6-a459-c0319144125c.png)

이 현상은 JGRPP 0.45.1, 정식버전 12.1 에서 확인되었습니다

**Comment by telk5093** [comment]
Duplicated of #15
