### ISSUE TITLE
슈퍼 에어로시티 → 뉴 슈퍼 에어로시티 F/L

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanBusSet#21]
현재 "슈퍼 에어로시티"로 이름붙여져 있는 스프라이트는 실제로는 "뉴 슈퍼 에어로시티 F/L"입니다.

[참고 링크](https://namu.wiki/w/%ED%98%84%EB%8C%80%20%EC%8A%88%ED%8D%BC%20%EC%97%90%EC%96%B4%EB%A1%9C%EC%8B%9C%ED%8B%B0)

**Comment by telk5093** [comment]
1. F/L(페이스리프트; Facelift)는 이름에 아직 반영할 계획이 없고
2. 외래어 표기법을 따르고
3. "저상" 표기는 유지하여
``뉴 수퍼 에어로시티 저상``으로 반영하겠습니다.
이마저도 잘못된 명칭인 경우, 별도 이슈로 알려주시면 감사하겠습니다.
