### ISSUE TITLE
대우저상

### ISSUE THREAD

**Issue by kimgas** [KoreanGRF/KoreanBusSet#5]
![daewoo_low](https://user-images.githubusercontent.com/79271602/113018334-66877f80-91bb-11eb-9a49-b4e66429a1fd.png)

2012~2014

**Comment by telk5093** [comment]
@kimgas [자일대우의 BC211M 또는 New BC211](https://ko.wikipedia.org/wiki/%EC%9E%90%EC%9D%BC%EB%8C%80%EC%9A%B0_BC)) 모델이 맞나요?
